apiVersion: v1
kind: Secret
metadata:
  name: solara-secrets
  labels:
    app: solara
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "admin_user"
  SPRING_DATASOURCE_PASSWORD: "REPLACE_WITH_DB_PASSWORD"
  APP_INTERNAL_API_KEY: "REPLACE_WITH_INTERNAL_API_KEY"
  APP_SETTINGS_API_KEY: "REPLACE_WITH_INTERNAL_API_KEY"
