apiVersion: v1
kind: Secret
metadata:
  name: solara-secrets
  labels:
    app: solara
type: Opaque
stringData:
  JWT_PRIVATE_KEY: "REPLACE_WITH_PRIVATE_KEY"
  JWT_PUBLIC_KEY: "REPLACE_WITH_PUBLIC_KEY"
  SPRING_DATASOURCE_USERNAME: "admin_user"
  SPRING_DATASOURCE_PASSWORD: "REPLACE_WITH_DB_PASSWORD"
  APP_INTERNAL_API_KEY: "REPLACE_WITH_INTERNAL_API_KEY"
