-- =============================================================================
-- Seed merchant_knowledge_base with curated popular merchants (one-off seed)
-- -----------------------------------------------------------------------------
-- Purpose:   Give the global KB coverage of well-known merchants BEFORE any
--            user has seen them, so MerchantResolver can answer instantly.
-- Scope:     ~500 well-known merchants — Indian + international (US/EU/SEA).
--            Aliases are PRE-NORMALIZED exactly as MerchantNormalizer outputs
--            (lowercase, non-alphanumeric → single space, trimmed): H&M → 'h m',
--            AT&T → 'a t t', Booking.com → 'booking com'.
-- Mapping:   Gyms → HEALTHCARE, insurance → BILLS_UTILITIES (recurring bills),
--            payment rails/remittance → OTHER, software subs → OTHER,
--            ride-hailing → TRANSPORT, fuel stations → FUEL,
--            apparel/footwear → CLOTHING, gadget/appliance stores → ELECTRONICS,
--            pet food/vet/supplies → PET, loan/EMI repayments → LOAN_EMI,
--            games/streaming/books → ENTERTAINMENT.
-- Evidence:  Seeds are HUMAN-CURATED labels, not LLM learning. transaction_count
--            = 1 signals a single curated observation (honest: real learnAlias
--            upserts will strengthen/override via the consensus average).
-- Idempotent: ON CONFLICT (alias) DO NOTHING — existing learned aliases are
--            never overwritten or diluted.
-- Re-run:    Safe any number of times (grew 122 → 501 rows on 2026-08-07).
-- Run:       docker exec -i insight-service-db psql -U admin_user -d db < scripts/seed-merchant-kb.sql
-- =============================================================================

INSERT INTO merchant_knowledge_base (id, alias, canonical_name, category, confidence, transaction_count, created_at)
SELECT gen_random_uuid(), v.alias, v.canonical_name, v.category, v.confidence, 1, now()
FROM (VALUES
    -- FOOD_DINING
    ('swiggy',            'Swiggy',            'FOOD_DINING',     0.95),
    ('zomato',            'Zomato',            'FOOD_DINING',     0.95),
    ('kfc',               'KFC',               'FOOD_DINING',     0.95),
    ('mcdonalds',         'McDonalds',         'FOOD_DINING',     0.95),
    ('burger king',       'Burger King',       'FOOD_DINING',     0.95),
    ('subway',            'Subway',            'FOOD_DINING',     0.95),
    ('pizza hut',         'Pizza Hut',         'FOOD_DINING',     0.95),
    ('starbucks',         'Starbucks',         'FOOD_DINING',     0.95),
    ('cafe coffee day',   'Cafe Coffee Day',   'FOOD_DINING',     0.95),
    ('haldirams',         'Haldirams',         'FOOD_DINING',     0.95),
    ('bikanervala',       'Bikanervala',       'FOOD_DINING',     0.95),
    ('barbeque nation',   'Barbeque Nation',   'FOOD_DINING',     0.95),
    ('wow momo',          'Wow Momo',          'FOOD_DINING',     0.95),
    ('faasos',            'Faasos',            'FOOD_DINING',     0.95),
    ('eat fit',           'EatFit',            'FOOD_DINING',     0.95),
    ('paradise biryani',  'Paradise Biryani',  'FOOD_DINING',     0.95),
    ('saravana bhavan',   'Saravana Bhavan',   'FOOD_DINING',     0.95),
    ('a2b',               'A2B',               'FOOD_DINING',     0.95),
    ('adyar anand bhavan','Adyar Anand Bhavan','FOOD_DINING',     0.95),

    -- GROCERIES
    ('dmart',             'DMart',             'GROCERIES',       0.95),
    ('bigbasket',         'BigBasket',         'GROCERIES',       0.95),
    ('blinkit',           'Blinkit',           'GROCERIES',       0.95),
    ('zepto',             'Zepto',             'GROCERIES',       0.95),
    ('instamart',         'Instamart',         'GROCERIES',       0.95),
    ('jiomart',           'JioMart',           'GROCERIES',       0.95),
    ('reliance fresh',    'Reliance Fresh',    'GROCERIES',       0.95),
    ('more supermarket',  'More Supermarket',  'GROCERIES',       0.95),
    ('safal',             'Safal',             'GROCERIES',       0.95),
    ('licious',           'Licious',           'GROCERIES',       0.95),
    ('amazon fresh',      'Amazon Fresh',      'GROCERIES',       0.95),

    -- SHOPPING
    ('amazon',            'Amazon',            'SHOPPING',        0.95),
    ('flipkart',          'Flipkart',          'SHOPPING',        0.95),
    ('myntra',            'Myntra',            'SHOPPING',        0.95),
    ('ajio',              'AJIO',              'SHOPPING',        0.95),
    ('meesho',            'Meesho',            'SHOPPING',        0.95),
    ('nykaa',             'Nykaa',             'SHOPPING',        0.95),
    ('reliance trends',   'Reliance Trends',   'SHOPPING',        0.95),
    ('decathlon',         'Decathlon',         'SHOPPING',        0.95),
    ('croma',             'Croma',             'SHOPPING',        0.95),
    ('vijay sales',       'Vijay Sales',       'SHOPPING',        0.95),
    ('shoppers stop',     'Shoppers Stop',     'SHOPPING',        0.95),
    ('westside',          'Westside',          'SHOPPING',        0.95),
    ('lifestyle',         'Lifestyle',         'SHOPPING',        0.95),
    ('max fashion',       'Max Fashion',       'SHOPPING',        0.95),
    ('fabindia',          'Fabindia',          'SHOPPING',        0.95),

    -- ENTERTAINMENT
    ('netflix',           'Netflix',           'ENTERTAINMENT',   0.95),
    ('prime video',       'Prime Video',       'ENTERTAINMENT',   0.95),
    ('amazon prime',      'Amazon Prime',      'ENTERTAINMENT',   0.95),
    ('spotify',           'Spotify',           'ENTERTAINMENT',   0.95),
    ('youtube premium',   'YouTube Premium',   'ENTERTAINMENT',   0.95),
    ('hotstar',           'Hotstar',           'ENTERTAINMENT',   0.95),
    ('disney hotstar',    'Disney+ Hotstar',   'ENTERTAINMENT',   0.95),
    ('bookmyshow',        'BookMyShow',        'ENTERTAINMENT',   0.95),
    ('pvr cinemas',       'PVR Cinemas',       'ENTERTAINMENT',   0.95),
    ('inox',              'INOX',              'ENTERTAINMENT',   0.95),
    ('jiocinema',         'JioCinema',         'ENTERTAINMENT',   0.95),
    ('apple tv',          'Apple TV',          'ENTERTAINMENT',   0.95),
    ('audible',           'Audible',           'ENTERTAINMENT',   0.95),
    ('wynk music',        'Wynk Music',        'ENTERTAINMENT',   0.95),
    ('gaana',             'Gaana',             'ENTERTAINMENT',   0.95),

    -- BILLS_UTILITIES
    ('jio',               'Jio',               'BILLS_UTILITIES', 0.95),
    ('airtel',            'Airtel',            'BILLS_UTILITIES', 0.95),
    ('vi',                'Vi',                'BILLS_UTILITIES', 0.95),
    ('bsnl',              'BSNL',              'BILLS_UTILITIES', 0.95),
    ('bescom',            'BESCOM',            'BILLS_UTILITIES', 0.95),
    ('bses',              'BSES',              'BILLS_UTILITIES', 0.95),
    ('tata power',        'Tata Power',        'BILLS_UTILITIES', 0.95),
    ('adani electricity', 'Adani Electricity', 'BILLS_UTILITIES', 0.95),
    ('mahanagar gas',     'Mahanagar Gas',     'BILLS_UTILITIES', 0.95),
    ('indane gas',        'Indane Gas',        'BILLS_UTILITIES', 0.95),
    ('hp gas',            'HP Gas',            'BILLS_UTILITIES', 0.95),
    ('bharat gas',        'Bharat Gas',        'BILLS_UTILITIES', 0.95),

    -- TRANSPORT (ride-hailing, transit, fastag)
    ('uber',              'Uber',              'TRANSPORT',       0.95),
    ('ola',               'Ola',               'TRANSPORT',       0.95),
    ('rapido',            'Rapido',            'TRANSPORT',       0.95),
    ('redbus',            'RedBus',            'TRANSPORT',       0.95),
    ('abhibus',           'AbhiBus',           'TRANSPORT',       0.95),
    ('nhaifastag',        'NHAI Fastag',       'TRANSPORT',       0.95),
    ('paytm fastag',      'Paytm Fastag',      'TRANSPORT',       0.95),

    -- FUEL (fuel stations)
    ('indian oil',        'Indian Oil',        'FUEL',            0.95),
    ('hp petrol',         'HP Petrol',         'FUEL',            0.95),
    ('bharat petroleum',  'Bharat Petroleum',  'FUEL',            0.95),
    ('shell petrol',      'Shell Petrol',      'FUEL',            0.95),
    ('reliance petroleum','Reliance Petroleum','FUEL',            0.95),
    ('jio bp',            'Jio-bp',            'FUEL',            0.95),
    ('nayara energy',     'Nayara Energy',     'FUEL',            0.95),

    -- TRAVEL
    ('irctc',             'IRCTC',             'TRAVEL',          0.95),
    ('makemytrip',        'MakeMyTrip',        'TRAVEL',          0.95),
    ('goibibo',           'Goibibo',           'TRAVEL',          0.95),
    ('yatra',             'Yatra',             'TRAVEL',          0.95),
    ('cleartrip',         'ClearTrip',         'TRAVEL',          0.95),
    ('indigo',            'IndiGo',            'TRAVEL',          0.95),
    ('air india',         'Air India',         'TRAVEL',          0.95),
    ('vistara',           'Vistara',           'TRAVEL',          0.95),
    ('spicejet',          'SpiceJet',          'TRAVEL',          0.95),
    ('akasa air',         'Akasa Air',         'TRAVEL',          0.95),
    ('oyo',               'OYO',               'TRAVEL',          0.95),
    ('airbnb',            'Airbnb',            'TRAVEL',          0.95),

    -- HEALTHCARE
    ('apollo pharmacy',   'Apollo Pharmacy',   'HEALTHCARE',      0.95),
    ('1mg',               '1mg',               'HEALTHCARE',      0.95),
    ('netmeds',           'Netmeds',           'HEALTHCARE',      0.95),
    ('pharmeasy',         'PharmEasy',         'HEALTHCARE',      0.95),
    ('medplus',           'MedPlus',           'HEALTHCARE',      0.95),
    ('apollo hospitals',  'Apollo Hospitals',  'HEALTHCARE',      0.95),
    ('fortis',            'Fortis',            'HEALTHCARE',      0.95),
    ('max hospital',      'Max Hospital',      'HEALTHCARE',      0.95),

    -- EDUCATION
    ('byjus',             'Byjus',             'EDUCATION',       0.95),
    ('udemy',             'Udemy',             'EDUCATION',       0.95),
    ('coursera',          'Coursera',          'EDUCATION',       0.95),
    ('unacademy',         'Unacademy',         'EDUCATION',       0.95),
    ('vedantu',           'Vedantu',           'EDUCATION',       0.95),
    ('physics wallah',    'Physics Wallah',    'EDUCATION',       0.95),
    ('upgrad',            'UpGrad',            'EDUCATION',       0.95),
    ('great learning',    'Great Learning',    'EDUCATION',       0.95),

    -- INVESTMENT
    ('zerodha',           'Zerodha',           'INVESTMENT',      0.95),
    ('groww',             'Groww',             'INVESTMENT',      0.95),
    ('etmoney',           'ETMoney',           'INVESTMENT',      0.95),
    ('kuvera',            'Kuvera',            'INVESTMENT',      0.95),
    ('angel one',         'Angel One',         'INVESTMENT',      0.95),
    ('upstox',            'Upstox',            'INVESTMENT',      0.95),
    ('paytm money',       'Paytm Money',       'INVESTMENT',      0.95),
    ('icici direct',      'ICICI Direct',      'INVESTMENT',      0.95),

    -- CLOTHING (apparel, footwear, accessories)
    ('myntra',            'Myntra',            'CLOTHING',        0.95),
    ('ajio',              'AJIO',              'CLOTHING',        0.95),
    ('flipkart fashion',  'Flipkart Fashion',  'CLOTHING',        0.95),
    ('zara',              'Zara',              'CLOTHING',        0.95),
    ('h m',               'H&M',               'CLOTHING',        0.95),
    ('uniqlo',            'UNIQLO',            'CLOTHING',        0.95),
    ('levis',             'Levi''s',           'CLOTHING',        0.95),
    ('nike',              'Nike',              'CLOTHING',        0.95),
    ('adidas',            'Adidas',            'CLOTHING',        0.95),
    ('puma',              'Puma',              'CLOTHING',        0.95),
    ('reebok',            'Reebok',            'CLOTHING',        0.95),
    ('van heusen',        'Van Heusen',        'CLOTHING',        0.95),
    ('allen solly',       'Allen Solly',       'CLOTHING',        0.95),
    ('peter england',     'Peter England',     'CLOTHING',        0.95),
    ('pantaloons',        'Pantaloons',        'CLOTHING',        0.95),
    ('westside',          'Westside',          'CLOTHING',        0.95),
    ('max fashion',       'Max Fashion',       'CLOTHING',        0.95),
    ('jockey',            'Jockey',            'CLOTHING',        0.95),

    -- ELECTRONICS (gadgets, appliances)
    ('croma',             'Croma',             'ELECTRONICS',     0.95),
    ('vijay sales',       'Vijay Sales',       'ELECTRONICS',     0.95),
    ('boat',              'boAt',              'ELECTRONICS',     0.95),
    ('apple store',       'Apple Store',       'ELECTRONICS',     0.95),
    ('samsung',           'Samsung',           'ELECTRONICS',     0.95),
    ('mi store',          'Mi Store',          'ELECTRONICS',     0.95),
    ('oneplus',           'OnePlus',           'ELECTRONICS',     0.95),
    ('jbl',               'JBL',               'ELECTRONICS',     0.95),
    ('lenovo',            'Lenovo',            'ELECTRONICS',     0.95),
    ('dell',              'Dell',              'ELECTRONICS',     0.95),
    ('hp',                'HP',                'ELECTRONICS',     0.95),
    ('lg',                'LG',                'ELECTRONICS',     0.95),
    ('sony',              'Sony',              'ELECTRONICS',     0.95),
    ('reliance digital',  'Reliance Digital',  'ELECTRONICS',     0.95),

    -- PET (food, vet, supplies)
    ('supertails',        'Supertails',        'PET',             0.95),
    ('heads up for tails','Heads Up For Tails','PET',             0.95),
    ('petsy',             'Petsy',             'PET',             0.95),
    ('tail waggers',      'Tail Waggers',      'PET',             0.95),
    ('doggypaw',          'DoggyPaw',          'PET',             0.95),
    ('petzone',           'Petzone',           'PET',             0.95),

    -- LOAN_EMI (loan and EMI repayments)
    ('bajaj finserv',     'Bajaj Finserv',     'LOAN_EMI',        0.95),
    ('bajaj finance',     'Bajaj Finance',     'LOAN_EMI',        0.95),
    ('eminet',            'EMI Network',       'LOAN_EMI',        0.95),
    ('tata capital',      'Tata Capital',      'LOAN_EMI',        0.95),
    ('hero fincorp',      'Hero FinCorp',      'LOAN_EMI',        0.95),
    ('hdb financial',     'HDB Financial',     'LOAN_EMI',        0.95),
    ('chola',             'Chola',             'LOAN_EMI',        0.95),
    ('fullerton india',   'Fullerton India',   'LOAN_EMI',        0.95),

    -- OTHER (payment mechanisms / transfers / software subs)
    ('paytm',             'Paytm',             'OTHER',           0.95),
    ('phonepe',           'PhonePe',           'OTHER',           0.95),
    ('cred',              'CRED',              'OTHER',           0.95),
    ('mobikwik',          'MobiKwik',          'OTHER',           0.95),

    -- ============ FOOD_DINING (international chains) ============
    ('taco bell',         'Taco Bell',         'FOOD_DINING',     0.95),
    ('chipotle',          'Chipotle',          'FOOD_DINING',     0.95),
    ('wendys',            'Wendys',            'FOOD_DINING',     0.95),
    ('wendy s',           'Wendys',            'FOOD_DINING',     0.95),
    ('dunkin donuts',     'Dunkin Donuts',     'FOOD_DINING',     0.95),
    ('krispy kreme',      'Krispy Kreme',      'FOOD_DINING',     0.95),
    ('tim hortons',       'Tim Hortons',       'FOOD_DINING',     0.95),
    ('five guys',         'Five Guys',         'FOOD_DINING',     0.95),
    ('shake shack',       'Shake Shack',       'FOOD_DINING',     0.95),
    ('papa johns',        'Papa Johns',        'FOOD_DINING',     0.95),
    ('papa john s',       'Papa Johns',        'FOOD_DINING',     0.95),
    ('panera bread',      'Panera Bread',      'FOOD_DINING',     0.95),
    ('cheesecake factory','The Cheesecake Factory', 'FOOD_DINING', 0.95),
    ('olive garden',      'Olive Garden',      'FOOD_DINING',     0.95),
    ('panda express',     'Panda Express',     'FOOD_DINING',     0.95),
    ('dq',                'Dairy Queen',       'FOOD_DINING',     0.95),
    ('ihop',              'IHOP',              'FOOD_DINING',     0.95),
    ('dennys',            'Denny''s',          'FOOD_DINING',     0.95),
    ('wingstop',          'Wingstop',          'FOOD_DINING',     0.95),
    ('dominos',           'Domino''s',         'FOOD_DINING',     0.95),
    ('domino s',          'Domino''s',         'FOOD_DINING',     0.95),
    ('ubereats',          'Uber Eats',         'FOOD_DINING',     0.95),
    ('doordash',          'DoorDash',          'FOOD_DINING',     0.95),
    ('grubhub',           'Grubhub',           'FOOD_DINING',     0.95),
    ('deliveroo',         'Deliveroo',         'FOOD_DINING',     0.95),
    ('justeat',           'Just Eat',          'FOOD_DINING',     0.95),
    ('foodpanda',         'Foodpanda',         'FOOD_DINING',     0.95),
    ('costa coffee',      'Costa Coffee',      'FOOD_DINING',     0.95),
    ('pret a manger',     'Pret A Manger',     'FOOD_DINING',     0.95),
    ('greggs',            'Greggs',            'FOOD_DINING',     0.95),
    ('jack in the box',   'Jack in the Box',   'FOOD_DINING',     0.95),
    ('arbys',             'Arby''s',           'FOOD_DINING',     0.95),
    ('arby s',            'Arby''s',           'FOOD_DINING',     0.95),
    ('sonic drive in',    'Sonic Drive-In',    'FOOD_DINING',     0.95),
    ('little caesars',    'Little Caesars',    'FOOD_DINING',     0.95),
    ('cinnabon',          'Cinnabon',          'FOOD_DINING',     0.95),
    ('auntie annes',      'Auntie Anne''s',    'FOOD_DINING',     0.95),
    ('pf changs',         'P.F. Chang''s',     'FOOD_DINING',     0.95),
    ('chilis',            'Chili''s',          'FOOD_DINING',     0.95),
    ('texas roadhouse',   'Texas Roadhouse',   'FOOD_DINING',     0.95),
    ('outback steakhouse','Outback Steakhouse','FOOD_DINING',     0.95),
    ('applebees',         'Applebee''s',       'FOOD_DINING',     0.95),
    ('buffalo wild wings','Buffalo Wild Wings','FOOD_DINING',     0.95),
    ('blue bottle',       'Blue Bottle',       'FOOD_DINING',     0.95),
    ('peets coffee',      'Peet''s Coffee',    'FOOD_DINING',     0.95),
    ('sweetgreen',        'Sweetgreen',        'FOOD_DINING',     0.95),
    ('cava',              'Cava',              'FOOD_DINING',     0.95),
    ('cold stone',        'Cold Stone',        'FOOD_DINING',     0.95),
    ('baskin robbins',    'Baskin Robbins',    'FOOD_DINING',     0.95),
    ('carls jr',          'Carl''s Jr.',       'FOOD_DINING',     0.95),
    ('hardees',           'Hardee''s',         'FOOD_DINING',     0.95),
    ('whataburger',       'Whataburger',       'FOOD_DINING',     0.95),
    ('culvers',           'Culver''s',         'FOOD_DINING',     0.95),
    ('zaxbys',            'Zaxby''s',          'FOOD_DINING',     0.95),
    ('popeyes',           'Popeyes',           'FOOD_DINING',     0.95),
    ('el pollo loco',     'El Pollo Loco',     'FOOD_DINING',     0.95),
    ('jollibee',          'Jollibee',          'FOOD_DINING',     0.95),
    ('white castle',      'White Castle',      'FOOD_DINING',     0.95),
    ('coffee bean and tea leaf', 'The Coffee Bean & Tea Leaf', 'FOOD_DINING', 0.95),
    ('mcdonald s',        'McDonald''s',       'FOOD_DINING',     0.95),

    -- ============ GROCERIES (international) ============
    ('kroger',            'Kroger',            'GROCERIES',       0.95),
    ('safeway',           'Safeway',           'GROCERIES',       0.95),
    ('aldi',              'ALDI',              'GROCERIES',       0.95),
    ('trader joes',       'Trader Joe''s',     'GROCERIES',       0.95),
    ('whole foods',       'Whole Foods',       'GROCERIES',       0.95),
    ('tesco',             'Tesco',             'GROCERIES',       0.95),
    ('sainsburys',        'Sainsbury''s',      'GROCERIES',       0.95),
    ('lidl',              'Lidl',              'GROCERIES',       0.95),
    ('asda',              'ASDA',              'GROCERIES',       0.95),
    ('coles',             'Coles',             'GROCERIES',       0.95),
    ('woolworths',        'Woolworths',        'GROCERIES',       0.95),
    ('publix',            'Publix',            'GROCERIES',       0.95),
    ('albertsons',        'Albertsons',        'GROCERIES',       0.95),
    ('wegmans',           'Wegmans',           'GROCERIES',       0.95),
    ('meijer',            'Meijer',            'GROCERIES',       0.95),
    ('giant eagle',       'Giant Eagle',       'GROCERIES',       0.95),
    ('food lion',         'Food Lion',         'GROCERIES',       0.95),
    ('sprouts farmers market', 'Sprouts Farmers Market', 'GROCERIES', 0.95),
    ('h mart',            'H Mart',            'GROCERIES',       0.95),
    ('waitrose',          'Waitrose',          'GROCERIES',       0.95),
    ('carrefour',         'Carrefour',         'GROCERIES',       0.95),
    ('mercadona',         'Mercadona',         'GROCERIES',       0.95),

    -- ============ SHOPPING (international) ============
    ('walmart',           'Walmart',           'SHOPPING',        0.95),
    ('target',            'Target',            'SHOPPING',        0.95),
    ('costco',            'Costco',            'SHOPPING',        0.95),
    ('sams club',         'Sam''s Club',       'SHOPPING',        0.95),
    ('ebay',              'eBay',              'SHOPPING',        0.95),
    ('etsy',              'Etsy',              'SHOPPING',        0.95),
    ('ikea',              'IKEA',              'SHOPPING',        0.95),
    ('home depot',        'The Home Depot',    'SHOPPING',        0.95),
    ('lowes',             'Lowe''s',           'SHOPPING',        0.95),
    ('best buy',          'Best Buy',          'SHOPPING',        0.95),
    ('apple',             'Apple Store',       'SHOPPING',        0.95),
    ('sephora',           'Sephora',           'SHOPPING',        0.95),
    ('nordstrom',         'Nordstrom',         'SHOPPING',        0.95),
    ('macys',             'Macy''s',           'SHOPPING',        0.95),
    ('bloomingdales',     'Bloomingdale''s',   'SHOPPING',        0.95),
    ('zara',              'Zara',              'SHOPPING',        0.95),
    ('h m',               'H&M',               'SHOPPING',        0.95),
    ('h and m',           'H&M',               'SHOPPING',        0.95),
    ('hm',                'H&M',               'SHOPPING',        0.95),
    ('uniqlo',            'Uniqlo',            'SHOPPING',        0.95),
    ('gap',               'Gap',               'SHOPPING',        0.95),
    ('old navy',          'Old Navy',          'SHOPPING',        0.95),
    ('nike',              'Nike',              'SHOPPING',        0.95),
    ('adidas',            'Adidas',            'SHOPPING',        0.95),
    ('footlocker',        'Foot Locker',       'SHOPPING',        0.95),
    ('marshalls',         'Marshalls',         'SHOPPING',        0.95),
    ('tj maxx',           'T.J. Maxx',         'SHOPPING',        0.95),
    ('kohls',             'Kohl''s',           'SHOPPING',        0.95),
    ('jcpenney',          'JCPenney',          'SHOPPING',        0.95),
    ('dollar tree',       'Dollar Tree',       'SHOPPING',        0.95),
    ('dollar general',    'Dollar General',    'SHOPPING',        0.95),
    ('newegg',            'Newegg',            'SHOPPING',        0.95),
    ('abercrombie',       'Abercrombie',       'SHOPPING',        0.95),
    ('american eagle',    'American Eagle',    'SHOPPING',        0.95),
    ('levis',             'Levi''s',           'SHOPPING',        0.95),
    ('victoria s secret', 'Victoria''s Secret','SHOPPING',        0.95),
    ('bath body works',   'Bath & Body Works', 'SHOPPING',        0.95),
    ('ulta beauty',       'Ulta Beauty',       'SHOPPING',        0.95),
    ('alibaba',           'Alibaba',           'SHOPPING',        0.95),
    ('taobao',            'Taobao',            'SHOPPING',        0.95),
    ('shein',             'Shein',             'SHOPPING',        0.95),
    ('temu',              'Temu',              'SHOPPING',        0.95),
    ('aliexpress',        'AliExpress',        'SHOPPING',        0.95),
    ('google store',      'Google Store',      'SHOPPING',        0.95),
    ('samsung',           'Samsung',           'SHOPPING',        0.95),
    ('wayfair',           'Wayfair',           'SHOPPING',        0.95),
    ('crate and barrel',  'Crate & Barrel',    'SHOPPING',        0.95),
    ('pottery barn',      'Pottery Barn',      'SHOPPING',        0.95),
    ('rei',               'REI',               'SHOPPING',        0.95),
    ('bass pro shops',    'Bass Pro Shops',    'SHOPPING',        0.95),
    ('staples',           'Staples',           'SHOPPING',        0.95),
    ('office depot',      'Office Depot',      'SHOPPING',        0.95),
    ('petco',             'Petco',             'SHOPPING',        0.95),
    ('petsmart',          'PetSmart',          'SHOPPING',        0.95),
    ('lego',              'LEGO',              'SHOPPING',        0.95),
    ('neiman marcus',     'Neiman Marcus',     'SHOPPING',        0.95),
    ('saks fifth avenue', 'Saks Fifth Avenue', 'SHOPPING',        0.95),
    ('guess',             'Guess',             'SHOPPING',        0.95),
    ('calvin klein',      'Calvin Klein',      'SHOPPING',        0.95),
    ('tommy hilfiger',    'Tommy Hilfiger',    'SHOPPING',        0.95),
    ('hollister',         'Hollister',         'SHOPPING',        0.95),
    ('aerie',             'Aerie',             'SHOPPING',        0.95),
    ('urban outfitters',  'Urban Outfitters',  'SHOPPING',        0.95),
    ('cotton on',         'Cotton On',         'SHOPPING',        0.95),

    -- ============ ENTERTAINMENT (international) ============
    ('disney plus',       'Disney+',           'ENTERTAINMENT',   0.95),
    ('hbo max',           'HBO Max',           'ENTERTAINMENT',   0.95),
    ('hulu',              'Hulu',              'ENTERTAINMENT',   0.95),
    ('paramount plus',    'Paramount+',        'ENTERTAINMENT',   0.95),
    ('peacock',           'Peacock',           'ENTERTAINMENT',   0.95),
    ('apple music',       'Apple Music',       'ENTERTAINMENT',   0.95),
    ('amazon music',      'Amazon Music',      'ENTERTAINMENT',   0.95),
    ('twitch',            'Twitch',            'ENTERTAINMENT',   0.95),
    ('patreon',           'Patreon',           'ENTERTAINMENT',   0.95),
    ('crunchyroll',       'Crunchyroll',       'ENTERTAINMENT',   0.95),
    ('steam',             'Steam',             'ENTERTAINMENT',   0.95),
    ('playstation',       'PlayStation',       'ENTERTAINMENT',   0.95),
    ('xbox',              'Xbox',              'ENTERTAINMENT',   0.95),
    ('nintendo',          'Nintendo',          'ENTERTAINMENT',   0.95),
    ('epic games',        'Epic Games',        'ENTERTAINMENT',   0.95),
    ('roblox',            'Roblox',            'ENTERTAINMENT',   0.95),
    ('fandango',          'Fandango',          'ENTERTAINMENT',   0.95),
    ('amc theatres',      'AMC Theatres',      'ENTERTAINMENT',   0.95),
    ('regal cinemas',     'Regal Cinemas',     'ENTERTAINMENT',   0.95),
    ('cineworld',         'Cineworld',         'ENTERTAINMENT',   0.95),
    ('barnes noble',      'Barnes & Noble',    'ENTERTAINMENT',   0.95),
    ('waterstones',       'Waterstones',       'ENTERTAINMENT',   0.95),
    ('google play',       'Google Play',       'ENTERTAINMENT',   0.95),
    ('tidal',             'Tidal',             'ENTERTAINMENT',   0.95),
    ('deezer',            'Deezer',            'ENTERTAINMENT',   0.95),
    ('soundcloud',        'SoundCloud',        'ENTERTAINMENT',   0.95),
    ('pandora',           'Pandora',           'ENTERTAINMENT',   0.95),
    ('discovery plus',    'Discovery+',        'ENTERTAINMENT',   0.95),
    ('sling tv',          'Sling TV',          'ENTERTAINMENT',   0.95),
    ('fubo',              'Fubo',              'ENTERTAINMENT',   0.95),
    ('youtube tv',        'YouTube TV',        'ENTERTAINMENT',   0.95),
    ('riot games',        'Riot Games',        'ENTERTAINMENT',   0.95),
    ('kindle unlimited',  'Kindle Unlimited',  'ENTERTAINMENT',   0.95),
    ('britbox',           'BritBox',           'ENTERTAINMENT',   0.95),
    ('mubi',              'Mubi',              'ENTERTAINMENT',   0.95),
    ('kobo',              'Kobo',              'ENTERTAINMENT',   0.95),

    -- ============ BILLS_UTILITIES (international; insurance = recurring bills) ============
    ('verizon',           'Verizon',           'BILLS_UTILITIES', 0.95),
    ('a t t',             'AT&T',              'BILLS_UTILITIES', 0.95),
    ('t mobile',          'T-Mobile',          'BILLS_UTILITIES', 0.95),
    ('comcast',           'Comcast',           'BILLS_UTILITIES', 0.95),
    ('xfinity',           'Xfinity',           'BILLS_UTILITIES', 0.95),
    ('spectrum',          'Spectrum',          'BILLS_UTILITIES', 0.95),
    ('cox communications','Cox Communications','BILLS_UTILITIES', 0.95),
    ('frontier',          'Frontier',          'BILLS_UTILITIES', 0.95),
    ('con edison',        'Con Edison',        'BILLS_UTILITIES', 0.95),
    ('p g e',             'PG&E',              'BILLS_UTILITIES', 0.95),
    ('duke energy',       'Duke Energy',       'BILLS_UTILITIES', 0.95),
    ('national grid',     'National Grid',     'BILLS_UTILITIES', 0.95),
    ('vodafone',          'Vodafone',          'BILLS_UTILITIES', 0.95),
    ('o2',                'O2',                'BILLS_UTILITIES', 0.95),
    ('orange',            'Orange',            'BILLS_UTILITIES', 0.95),
    ('deutsche telekom',  'Deutsche Telekom',  'BILLS_UTILITIES', 0.95),
    ('bt',                'BT',                'BILLS_UTILITIES', 0.95),
    ('sky uk',            'Sky UK',            'BILLS_UTILITIES', 0.95),
    ('virgin media',      'Virgin Media',      'BILLS_UTILITIES', 0.95),
    ('ee',                'EE',                'BILLS_UTILITIES', 0.95),
    ('british gas',       'British Gas',       'BILLS_UTILITIES', 0.95),
    ('geico',             'GEICO',             'BILLS_UTILITIES', 0.95),
    ('progressive',       'Progressive',       'BILLS_UTILITIES', 0.95),
    ('state farm',        'State Farm',        'BILLS_UTILITIES', 0.95),
    ('allstate',          'Allstate',          'BILLS_UTILITIES', 0.95),
    ('lemonade',          'Lemonade',          'BILLS_UTILITIES', 0.95),
    ('acko',              'Acko',              'BILLS_UTILITIES', 0.95),
    ('policybazaar',      'PolicyBazaar',      'BILLS_UTILITIES', 0.95),
    ('xcel energy',       'Xcel Energy',       'BILLS_UTILITIES', 0.95),
    ('edf',               'EDF',               'BILLS_UTILITIES', 0.95),
    ('starlink',          'Starlink',          'BILLS_UTILITIES', 0.95),
    ('mint mobile',       'Mint Mobile',       'BILLS_UTILITIES', 0.95),
    ('cricket wireless',  'Cricket Wireless',  'BILLS_UTILITIES', 0.95),
    ('metro pcs',         'Metro PCS',         'BILLS_UTILITIES', 0.95),
    ('boost mobile',      'Boost Mobile',      'BILLS_UTILITIES', 0.95),
    ('liberty mutual',    'Liberty Mutual',    'BILLS_UTILITIES', 0.95),
    ('farmers insurance', 'Farmers Insurance', 'BILLS_UTILITIES', 0.95),
    ('nationwide',        'Nationwide',        'BILLS_UTILITIES', 0.95),

    -- ============ TRANSPORT (international; ride-hailing, rental) ============
    ('lyft',              'Lyft',              'TRANSPORT',       0.95),
    ('bolt',              'Bolt',              'TRANSPORT',       0.95),
    ('didi',              'DiDi',              'TRANSPORT',       0.95),
    ('grab',              'Grab',              'TRANSPORT',       0.95),
    ('gojek',             'Gojek',             'TRANSPORT',       0.95),
    ('zipcar',            'Zipcar',            'TRANSPORT',       0.95),
    ('turo',              'Turo',              'TRANSPORT',       0.95),
    ('lime',              'Lime',              'TRANSPORT',       0.95),
    ('bird',              'Bird',              'TRANSPORT',       0.95),
    ('enterprise',        'Enterprise',        'TRANSPORT',       0.95),
    ('hertz',             'Hertz',             'TRANSPORT',       0.95),
    ('avis',              'Avis',              'TRANSPORT',       0.95),
    ('budget',            'Budget',            'TRANSPORT',       0.95),

    -- ============ FUEL (international) ============
    ('exxon',             'Exxon',             'FUEL',            0.95),
    ('bp',                'BP',                'FUEL',            0.95),
    ('chevron',           'Chevron',           'FUEL',            0.95),
    ('texaco',            'Texaco',            'FUEL',            0.95),
    ('shell',             'Shell',             'FUEL',            0.95),
    ('speedway',          'Speedway',          'FUEL',            0.95),
    ('marathon',          'Marathon',          'TRANSPORT',       0.95),
    ('citgo',             'CITGO',             'TRANSPORT',       0.95),
    ('murphy usa',        'Murphy USA',        'TRANSPORT',       0.95),
    ('circle k',          'Circle K',          'TRANSPORT',       0.95),

    -- ============ TRAVEL (international) ============
    ('booking com',       'Booking.com',       'TRAVEL',          0.95),
    ('expedia',           'Expedia',           'TRAVEL',          0.95),
    ('kayak',             'KAYAK',             'TRAVEL',          0.95),
    ('skyscanner',        'Skyscanner',        'TRAVEL',          0.95),
    ('priceline',         'Priceline',         'TRAVEL',          0.95),
    ('hotels com',        'Hotels.com',        'TRAVEL',          0.95),
    ('hostelworld',       'Hostelworld',       'TRAVEL',          0.95),
    ('united airlines',   'United Airlines',   'TRAVEL',          0.95),
    ('delta',             'Delta Air Lines',   'TRAVEL',          0.95),
    ('american airlines', 'American Airlines', 'TRAVEL',          0.95),
    ('southwest',         'Southwest Airlines','TRAVEL',          0.95),
    ('jetblue',           'JetBlue',           'TRAVEL',          0.95),
    ('alaska airlines',   'Alaska Airlines',   'TRAVEL',          0.95),
    ('air canada',        'Air Canada',        'TRAVEL',          0.95),
    ('lufthansa',         'Lufthansa',         'TRAVEL',          0.95),
    ('british airways',   'British Airways',   'TRAVEL',          0.95),
    ('qatar airways',     'Qatar Airways',     'TRAVEL',          0.95),
    ('emirates',          'Emirates',          'TRAVEL',          0.95),
    ('singapore airlines','Singapore Airlines','TRAVEL',          0.95),
    ('klm',               'KLM',               'TRAVEL',          0.95),
    ('air france',        'Air France',        'TRAVEL',          0.95),
    ('qantas',            'Qantas',            'TRAVEL',          0.95),
    ('turkish airlines',  'Turkish Airlines',  'TRAVEL',          0.95),
    ('ryanair',           'Ryanair',           'TRAVEL',          0.95),
    ('easyjet',           'easyJet',           'TRAVEL',          0.95),
    ('japan airlines',    'Japan Airlines',    'TRAVEL',          0.95),
    ('cathay pacific',    'Cathay Pacific',    'TRAVEL',          0.95),
    ('amtrak',            'Amtrak',            'TRAVEL',          0.95),
    ('eurostar',          'Eurostar',          'TRAVEL',          0.95),
    ('royal caribbean',   'Royal Caribbean',   'TRAVEL',          0.95),
    ('carnival',          'Carnival',          'TRAVEL',          0.95),
    ('marriott',          'Marriott',          'TRAVEL',          0.95),
    ('hilton',            'Hilton',            'TRAVEL',          0.95),
    ('hyatt',             'Hyatt',             'TRAVEL',          0.95),
    ('ihg',               'IHG Hotels',        'TRAVEL',          0.95),
    ('choice hotels',     'Choice Hotels',     'TRAVEL',          0.95),
    ('wyndham',           'Wyndham',           'TRAVEL',          0.95),
    ('accor',             'Accor',             'TRAVEL',          0.95),
    ('radisson',          'Radisson',          'TRAVEL',          0.95),
    ('four seasons',      'Four Seasons',      'TRAVEL',          0.95),
    ('korean air',        'Korean Air',        'TRAVEL',          0.95),
    ('ethiopian airlines','Ethiopian Airlines','TRAVEL',          0.95),
    ('trip com',          'Trip.com',          'TRAVEL',          0.95),
    ('norwegian cruise line', 'Norwegian Cruise Line', 'TRAVEL',  0.95),
    ('princess cruises',  'Princess Cruises',  'TRAVEL',          0.95),
    ('viator',            'Viator',            'TRAVEL',          0.95),
    ('getyourguide',      'GetYourGuide',      'TRAVEL',          0.95),
    ('klook',             'Klook',             'TRAVEL',          0.95),
    ('etihad',            'Etihad Airways',    'TRAVEL',          0.95),
    ('virgin atlantic',   'Virgin Atlantic',   'TRAVEL',          0.95),
    ('swiss',             'SWISS',             'TRAVEL',          0.95),

    -- ============ HEALTHCARE (international; pharmacies, clinics, gyms) ============
    ('cvs pharmacy',      'CVS Pharmacy',      'HEALTHCARE',      0.95),
    ('walgreens',         'Walgreens',         'HEALTHCARE',      0.95),
    ('rite aid',          'Rite Aid',          'HEALTHCARE',      0.95),
    ('boots',             'Boots',             'HEALTHCARE',      0.95),
    ('shoppers drug mart','Shoppers Drug Mart','HEALTHCARE',      0.95),
    ('kaiser permanente', 'Kaiser Permanente', 'HEALTHCARE',      0.95),
    ('mayo clinic',       'Mayo Clinic',       'HEALTHCARE',      0.95),
    ('headspace',         'Headspace',         'HEALTHCARE',      0.95),
    ('calm',              'Calm',              'HEALTHCARE',      0.95),
    ('betterhelp',        'BetterHelp',        'HEALTHCARE',      0.95),
    ('planet fitness',    'Planet Fitness',    'HEALTHCARE',      0.95),
    ('equinox',           'Equinox',           'HEALTHCARE',      0.95),
    ('la fitness',        'LA Fitness',        'HEALTHCARE',      0.95),
    ('anytime fitness',   'Anytime Fitness',   'HEALTHCARE',      0.95),
    ('24 hour fitness',   '24 Hour Fitness',   'HEALTHCARE',      0.95),
    ('golds gym',         'Gold''s Gym',       'HEALTHCARE',      0.95),
    ('crunch fitness',    'Crunch Fitness',    'HEALTHCARE',      0.95),
    ('orangetheory',      'Orangetheory',      'HEALTHCARE',      0.95),
    ('lenscrafters',      'LensCrafters',      'HEALTHCARE',      0.95),
    ('cleveland clinic',  'Cleveland Clinic',  'HEALTHCARE',      0.95),
    ('johns hopkins',     'Johns Hopkins',     'HEALTHCARE',      0.95),
    ('whoop',             'Whoop',             'HEALTHCARE',      0.95),

    -- ============ EDUCATION (international) ============
    ('edx',               'edX',               'EDUCATION',       0.95),
    ('udacity',           'Udacity',           'EDUCATION',       0.95),
    ('duolingo',          'Duolingo',          'EDUCATION',       0.95),
    ('babbel',            'Babbel',            'EDUCATION',       0.95),
    ('rosetta stone',     'Rosetta Stone',     'EDUCATION',       0.95),
    ('skillshare',        'Skillshare',        'EDUCATION',       0.95),
    ('masterclass',       'MasterClass',       'EDUCATION',       0.95),
    ('pluralsight',       'Pluralsight',       'EDUCATION',       0.95),
    ('linkedin learning', 'LinkedIn Learning', 'EDUCATION',       0.95),
    ('codecademy',        'Codecademy',        'EDUCATION',       0.95),
    ('datacamp',          'DataCamp',          'EDUCATION',       0.95),
    ('brilliant',         'Brilliant',         'EDUCATION',       0.95),
    ('chegg',             'Chegg',             'EDUCATION',       0.95),
    ('quizlet',           'Quizlet',           'EDUCATION',       0.95),
    ('pimsleur',          'Pimsleur',          'EDUCATION',       0.95),

    -- ============ INVESTMENT (international) ============
    ('robinhood',         'Robinhood',         'INVESTMENT',      0.95),
    ('charles schwab',    'Charles Schwab',    'INVESTMENT',      0.95),
    ('fidelity',          'Fidelity',          'INVESTMENT',      0.95),
    ('vanguard',          'Vanguard',          'INVESTMENT',      0.95),
    ('interactive brokers','Interactive Brokers','INVESTMENT',    0.95),
    ('etrade',            'E*TRADE',           'INVESTMENT',      0.95),
    ('wealthfront',       'Wealthfront',       'INVESTMENT',      0.95),
    ('betterment',        'Betterment',        'INVESTMENT',      0.95),
    ('acorns',            'Acorns',            'INVESTMENT',      0.95),
    ('coinbase',          'Coinbase',          'INVESTMENT',      0.95),
    ('binance',           'Binance',           'INVESTMENT',      0.95),
    ('kraken',            'Kraken',            'INVESTMENT',      0.95),
    ('gemini',            'Gemini',            'INVESTMENT',      0.95),
    ('webull',            'Webull',            'INVESTMENT',      0.95),
    ('sofi',              'SoFi',              'INVESTMENT',      0.95),
    ('m1 finance',        'M1 Finance',        'INVESTMENT',      0.95),
    ('tastytrade',        'tastytrade',        'INVESTMENT',      0.95),
    ('stash',             'Stash',             'INVESTMENT',      0.95),

    -- ============ OTHER (international; payment rails, remittance, software subs) ============
    ('paypal',            'PayPal',            'OTHER',           0.95),
    ('venmo',             'Venmo',             'OTHER',           0.95),
    ('cash app',          'Cash App',          'OTHER',           0.95),
    ('zelle',             'Zelle',             'OTHER',           0.95),
    ('revolut',           'Revolut',           'OTHER',           0.95),
    ('wise',              'Wise',              'OTHER',           0.95),
    ('western union',     'Western Union',     'OTHER',           0.95),
    ('moneygram',         'MoneyGram',         'OTHER',           0.95),
    ('remitly',           'Remitly',           'OTHER',           0.95),
    ('adobe',             'Adobe',             'OTHER',           0.95),
    ('microsoft 365',     'Microsoft 365',     'OTHER',           0.95),
    ('google one',        'Google One',        'OTHER',           0.95),
    ('icloud plus',       'iCloud+',           'OTHER',           0.95),
    ('dropbox',           'Dropbox',           'OTHER',           0.95),
    ('nordvpn',           'NordVPN',           'OTHER',           0.95),
    ('expressvpn',        'ExpressVPN',        'OTHER',           0.95),
    ('proton',            'Proton',            'OTHER',           0.95),
    ('alipay',            'Alipay',            'OTHER',           0.95),
    ('zoom',              'Zoom',              'OTHER',           0.95),
    ('grammarly',         'Grammarly',         'OTHER',           0.95),
    ('canva',             'Canva',             'OTHER',           0.95),
    ('notion',            'Notion',            'OTHER',           0.95),
    ('github',            'GitHub',            'OTHER',           0.95),
    ('xoom',              'Xoom',              'OTHER',           0.95),

    -- ============ INDIA (additional brands) ============
    ('tatasky',           'Tata Play',         'ENTERTAINMENT',   0.95),
    ('dishtv',            'DishTV',            'ENTERTAINMENT',   0.95),
    ('zee5',              'ZEE5',              'ENTERTAINMENT',   0.95),
    ('sonyliv',           'SonyLIV',           'ENTERTAINMENT',   0.95),
    ('taj hotels',        'Taj Hotels',        'TRAVEL',          0.95),
    ('oberoi',            'The Oberoi',        'TRAVEL',          0.95),
    ('itc hotels',        'ITC Hotels',        'TRAVEL',          0.95),

    -- ============ INDIA (resorts & hotel chains — proper-noun entities) ============
    ('taj malabar',       'Taj Malabar',       'TRAVEL',          0.95),
    ('clarks exotica',    'Clarks Exotica',    'TRAVEL',          0.95),
    ('zuri',              'Zuri Hotels & Resorts', 'TRAVEL',      0.95),
    ('club mahindra',     'Club Mahindra',     'TRAVEL',          0.95),
    ('treebo',            'Treebo',            'TRAVEL',          0.95),
    ('fabhotels',         'FabHotels',         'TRAVEL',          0.95),
    ('ramada',            'Ramada',            'TRAVEL',          0.95),
    ('novotel',           'Novotel',           'TRAVEL',          0.95),
    ('ibis',              'ibis',              'TRAVEL',          0.95),
    ('lemon tree',        'Lemon Tree Hotels', 'TRAVEL',          0.95),
    ('ginger hotels',     'Ginger Hotels',     'TRAVEL',          0.95),
    ('lalit',             'The Lalit',         'TRAVEL',          0.95)
) AS v(alias, canonical_name, category, confidence)
WHERE NOT EXISTS (SELECT 1 FROM merchant_knowledge_base)
ON CONFLICT (alias) DO NOTHING;
